### ISSUE TITLE
PCB

### ISSUE THREAD

**Issue by zabuldon** [YIO-Remote/remote-software#1]
Is it possible to share PCB as well?

**Comment by martonborzak** [comment]
Yes, I am working on an updated version. As soon as it's done and working I'll share the schematics and gerber files.

**Comment by martonborzak** [comment]
Hey @zabuldon, just uploaded a first draft of the schematics. It is not final, but almost :)

**Comment by zabuldon** [comment]
It would be nice to see BOM for PCB, I'm trying to reproduce this.

**Comment by martonborzak** [comment]
I am still testing some things. As soon as I locked down the parts, I'll upload it.
