### ISSUE TITLE
Error when building based on new .pro file

### ISSUE THREAD

**Issue by martonborzak** [YIO-Remote/remote-software#108]
I've tried it now, but got an error:
[copyConfig] Error 64

It's the .pro file that gives this. The rest of the code works fine.

Narrowed it down to this:
`QMAKE_EXTRA_TARGETS += first copyConfig copyTranslations`

_Originally posted by @martonborzak in https://github.com/martonborzak/yio-remote/pull/107#issuecomment-487213277_

**Comment by gvdhoven** [comment]
Did you fix this or not? Since you merged the pull request? Can you try this:
```
# Copy config file to output directory
copyConfig.commands = $(COPY_DIR) $$shell_path($$PWD/config.json) $$OUT_PWD
copyConfig.depends = copyTranslations

# Copy translation file to output directory
copyTranslations.commands = $(COPY_DIR) $$shell_path($$PWD/translations.json) $$OUT_PWD

# Add copy commands to build output
QMAKE_EXTRA_TARGETS += copyConfig copyTranslations
```
Taken from the [Qt documentation](https://doc.qt.io/qt-5/qmake-advanced-usage.html)

**Comment by martonborzak** [comment]
Haven't fixed it yet. This one gives no error, but doesn't copy the files.

**Comment by gvdhoven** [comment]
maybe there is a post-build step we can do on a mac to pull in those files. I'll see what i can do to fix it.

**Comment by martonborzak** [comment]
On a mac it can be done with the INSTALLS += that put's it in the bundle

**Comment by martonborzak** [comment]
I'll test it in the evening and push a version if it works.
