### ISSUE TITLE
Update software update helper bash script

### ISSUE THREAD

**Issue by martonborzak** [YIO-Remote/remote-software#120]
Currently the script just updates the remote app itself:
```
#!/bin/bash
fbv -d 1 /update.png
killall -9 python
killall -9 remote
sleep 2
cp /usr/bin/remote /usr/bin/remote-backup
rm -rf /usr/bin/remote
sleep 2
curl -L $1 > /usr/bin/remote
sleep 2
chmod +x /usr/bin/remote
/usr/bin/app-launch.sh &
```

It should be updated to pull a zip file, that contains all the helper scripts and config files, etc and replace everything that is inside /usr/bin/remote.

1. kill python and remote
2. make a backup of the /usr/bin/remote folder
3. delete the folder
4. download the URL that is given to the bash script > $1
4. extract the zip file to /usr/bin/remote
5. give executable permissions to all .sh files and the remote file
6. launch the remote app with the launcher bash script

**Comment by gvdhoven** [comment]
How about:
1. download the URL that is given to the bash script > $1
2. extract the zip file to /usr/bin/remote-(update-timestamp)
3. give executable permissions to all .sh files and the remote file
4. remove previous backups
5. make a backup of the /usr/bin/remote folder (if not already exist, maybe add timestamp to folder)
6. kill python and remote `by pid`
7. delete the /usr/bin/remote folder
8. rename the update folder to /usr/bin/remote
9. launch the remote app with the launcher bash script

This way, any failure between 1-5 won't leave the remote in limbo state.

**Comment by martonborzak** [comment]
Good idea! Do you want to make a pull request for this?

**Comment by gvdhoven** [comment]
I've did some work on it but it is untested since i don't have a pi with the correct software on it. It still might some work but should give you a headstart.
