### ISSUE TITLE
Detect touch events in Qt

### ISSUE THREAD

**Issue by martonborzak** [YIO-Remote/remote-software#130]
Looking into detecting touch events in Qt. I'm trying to port the python script to Qt so Qt itself would look at /dev/input/event0 and reset the display standby timer when a touch event is detected. Anyone has some time or ideas to look into this? :smiley:
[https://doc.qt.io/qt-5/qtouchevent.html](https://doc.qt.io/qt-5/qtouchevent.html)

**Comment by gvdhoven** [comment]
Based on Discord #coding channel (moved here for discussion reference);
There is a sample implementation in Qt; https://doc.qt.io/archives/qtopia4.3/tut-deviceexample.html

`The constructor opens the keyboard device, /dev/input/event0. A QSocketNotifier is used to get asynchronous notification on the availability of data from the device.`
