### ISSUE TITLE
Yio Remote FW 0.1 Bugs

### ISSUE THREAD

**Issue by carp3-noctem** [YIO-Remote/remote-software#228]
~~ - Language Selection: Deutsche needs to be Deutsch ~~
- German Language is used, Setting Reboot and Shutdown buttons are out of display range (showing in the next left / right entry)
- Uptime uses wrong time format (0:0:00 should be 00:00:00)
- ~using mediaplayer (autoplay) grapfic is cutted left and right to get the hight~
- ~navigation via direction keys leads to main menu stays in display leads to cutoff page at bottom (works when touchscreen is used)~
- ~Big headline within page disturbes clean look, small headline at top is enough~
- cleaning mode is deactivated
- wifi selection on remote leads to input field without functioning keyboard
- ~config page is available under yioremote.local - setting page shows ip (better reading)~
- CPU temp is shown in xx.xxx°C sometimes, can be cutted to xx -> less load?!?
- ~Battery Health Screentime get wrongly calculated and displayed~
- Wi-Fi signal strength is empty

**Comment by martonborzak** [comment]
> * using mediaplayer (autoplay) grapfic is cutted left and right to get the hight

The image comes in various formats, so the remote crops it to fit in the background. I'd say this is a feature :)

**Comment by martonborzak** [comment]
> * Language Selection: Deutsche needs to be Deutsch

~~This can be fixed on [crowdin](https://translate.yio-remote.com).~~

My bad. It was translations.json :) Fixed now.

**Comment by carp3-noctem** [comment]
> 
> 
> > * using mediaplayer (autoplay) grapfic is cutted left and right to get the hight
> 
> The image comes in various formats, so the remote crops it to fit in the background. I'd say this is a feature :)

Wouldn't it be better to display it in full width and crop / black stripe the height?

**Comment by martonborzak** [comment]
I've tried that but I'm not a big fan of black bars. Alternative option
could be to use a service to find an image with the right aspect ratio. I
did that with the movies.

**Comment by carp3-noctem** [comment]
You are right, black bars should always be the last step to use.
Maybe we should check out coverartarchive.org they seems to have images that are available via api and in the same formfactor.

**Comment by nklerk** [comment]
Would it be an idea to seperate the issues? this way we can better handle them

**Comment by martonborzak** [comment]
Good idea
