### ISSUE TITLE
Add a developer operation mode

### ISSUE THREAD

**Issue by wayfarer003** [YIO-Remote/remote-software#231]
On the physical hardware a couple of issues came up when running with partial hardware
- Without a battery at 0 charge the battery charge screen can not be dismissed
- With a battery but running on a bench power supply the 100% charge screen can not be dismissed.  This requires turning off the bench supply in order to use the remote (forces battery usage)

A developer mode could have the follow features
- disabled the battery charging screen to allow for partial HW configurations and bench power
- Always enable WiFi to allow for uploading code, system access
- console logging to LCD panel
- remote serial logging
- Other "things" that would not normally be used by a typical user

**Comment by zehnm** [comment]
This is on my TODO list as well :-)
Any preferences or ideas on how to activate developer mode? My thoughts so far:

- control file on /boot partition (Fat partition, mountable on any OS)
- switching config.txt and cmdline.txt on /boot partition (required to disable DPI display and use HDMI)
- configuration file
- specific button presses on boot enters developer mode

**Comment by martonborzak** [comment]
Thanks @zehnm ! :)

I think the developer mode is more useful when you're running the app on your PC or Mac.
You can run the code from Qt on the actual hardware and see all the console output on your host machine.

**Comment by martonborzak** [comment]
I think an option could be to select the dev mode on the remote and then it reboots into it. It's hard to detect button presses at boot, because you have to wait for the driver to load.

**Comment by martonborzak** [comment]
I think this will be solved with #346. What do you think @zehnm ?

**Comment by zehnm** [comment]
The hardware abstraction is not related to a developer mode. Certain things might be easier to reconfigure though.

**Comment by martonborzak** [comment]
Is there still a need for this mode? What do you think @zehnm ?
We have mock hardware things, so the app can run on any device without getting error messages for battery gauge, etc.

**Comment by wayfarer003** [comment]
After checking back into the project after some time.  If it is fairly simple to change modes / behavior without this feature then it would be ok in my mind to close or back burner this request.

**Comment by zehnm** [comment]
@martonborzak I think we can close this issue, especially with all the new configuration options.
The "real developer image" is covered in YIO-Remote/remote-os#11 which will add USB, other displays (e.g. Pimoroni Hyperpixel) and whatever seems required to play around with remote-software on a regular RPi.

**Comment by martonborzak** [comment]
Great, I'm closing this issue then.
