### ISSUE TITLE
Media controls naming proposal

### ISSUE THREAD

**Issue by nklerk** [YIO-Remote/remote-software#283]
To MAP Buttons to groups and keep naming concequent. this is a naming proposal.

** Transport and mediacontrolls
PLAY
PAUSE
PLAYTOGGLE
STOP
FORWARD
REVERSE
NEXT
PREVIOUS
INFO
RECORDINGS
RECORD
LIVE

** digits
DIGIT 0 
DIGIT 1
DIGIT 2
DIGIT 3
DIGIT 4
DIGIT 5
DIGIT 6
DIGIT 7
DIGIT 8
DIGIT 9
DIGIT 10  // Some countries use this button
DIGIT 10+// Some countries use this button
DIGIT 11  // Some countries use this button
DIGIT 12  // Some countries use this button
DIGIT SEPARATOR
DIGIT ENTER 

** Navigation
CURSOR UP
CURSOR DOWN
CURSOR LEFT
CURSOR RIGHT
CURSOR OK
BACK
HOME
MENU
EXIT
INFO
APP

** power
POWER OFF
POWER ON
POWER TOGGLE

** tuner
CHANNEL UP
CHANNEL DOWN
CHANNEL SEARCH
FAVORITE
GUIDE

** Interactive
FUNCTION RED
FUNCTION GREEN
FUNCTION YELLOW
FUNCTION BLUE
FUNCTION ORANGE

** video
FORMAT 16:9
FORMAT 4:3
FORMAT AUTO

** Volume
VOLUME UP
VOLUME DOWN
MUTE TOGGLE

** Input
INPUT TUNER 1
INPUT TUNER 2
INPUT TUNER ..
INPUT HDMI 1
INPUT HDMI 2
INPUT HDMI ..
INPUT .. 1
INPUT .. 2
INPUT .. ..

** Output
OUTPUT HDMI 1
OUTPUT HDMI 2
OUTPUT DVI 1
OUTPUT AUDIO ..
OUTPUT .. ..

** Services
SERVICE NETFLIX
SERVICE HULU
SERVICE PROVIDER
SERVICE ..

* Seperate button names to consider, I.E. for icons and such:

#
*
3D
ALT-F4
AUDIO
ANGLE
CANCEL
CAP LOCK
CLEAR
CLEAR QUEUE
CLR
DELETE
DIMMER
DIRECT TUNE
DISPLAY
MANUAL
KIOSK
LANGUAGE
LIVE TV
MESSENGER
MODE
MODE GAME 1
MODE MOVIE/TV
MODE MUSIC
MODE STEREO
MOUSE
MUTE
UNMUTE
APPS
MUSIC
PICTURES
SECURITY
VIDEOS
OPEN CLOSE
OPTIONS
OUTPUT RESOLUTION
PRINT
RADIO
RANDOM
REBOOT
REPEAT
REPEAT TOGGLE
REPLAY 10 SEC
SEARCH
SHUFFLE TOGGLE
SKIP BACKWARD
SKIP FORWARD
SLEEP
SPEAKER A
SPEAKER B
SUBTITLE
TELETEXT
TITLE
TONE
TONE +
TONE -
TOOLS
WRITE

**Comment by carp3-noctem** [comment]
List of Buttons from enigma2 Settop Receiver is available here:

https://docs.google.com/spreadsheets/d/1DlcXXRLvs-AKHAxlF2KolwLmICR3OC4liS-9Cn0K48c/edit#gid=0

**Comment by carp3-noctem** [comment]
Streaming Providers:
Amazon Video
Netflix
Hulu
YouTube
waipu.tv
sky
sling
vudu
appleTV
HBO now
.
.
.

**Comment by nklerk** [comment]
I propose “SERVICE ...” for steaming services just like input ...

**Comment by nklerk** [comment]
I've added missing name proposal. Added: SERVICE & OUTPUT.

**Comment by martonborzak** [comment]
Most of this is implemented. I'll remove the from the milestone and leave the issue open, so we can use it as a reference.
