### ISSUE TITLE
German Language is used, Setting Reboot and Shutdown buttons are out of display range (showing in the next left / right entry)

### ISSUE THREAD

**Issue by martonborzak** [YIO-Remote/remote-software#306]

**Comment by zehnm** [comment]
@carp3-noctem speaking about German: shouldn't the label be named "Deutsch" instead of "Deutsche"?
<img width="476" alt="YIO-select-language" src="https://user-images.githubusercontent.com/17356629/68384371-c4936d00-0157-11ea-9cfc-64272dd9a1b1.png">
