### ISSUE TITLE
Wifi selection is not working in settings

### ISSUE THREAD

**Issue by martonborzak** [YIO-Remote/remote-software#309]
- [x] wifi selection on remote leads to input field without functioning keyboard
- [x] Wi-Fi signal strength is empty
- [x] SSID name with spaces is not displayed correctly, only first word is shown

**Comment by zehnm** [comment]
The new WifiControl interface in feature/322-WiFi_rewrite is prepared to complete the UI interactions:
- startNetworkScan() operation to scan for available networks
- Qt signal & getter for a list of available networks including signal strength and encryption type
- Qt signal for wifi signal strength changes
- join() operation

Depends on #322 and either needs to be implemented and coordinated in the feature/322-WiFi_rewrite branch, or waited until #322 is merged in dev.
