### ISSUE TITLE
WiFi access point mode / Bluetooth transfer

### ISSUE THREAD

**Issue by gvdhoven** [YIO-Remote/remote-software#31]
Currently the remote scans for networks and allows you to choose one. In case you have multiple remotes (imagining a kickstarter pledge) you would have to repeat this process multiple times.

Having the remotes start in AP mode, would allow you to connect with one remote using your mobile device (iOS/Android), since it just serves a website; then post-setup the remote you’ve setup your WiFi with can scan for other YIO devices (remotes, or bases including ESP if this is added) and update the WiFi accordingly.

Flow wise; i would see something like this:
Out of box -> WiFi in AP mode -> Use mobile or tablet to go through easy wifi setup flow -> Remote shows ‘success’ -> Remote shows other YIO devices (in setup/AP mode) who have a specific YIO name in it -> User can select which devices to update -> Remote initiates WiFi credential push to these devices.

Extension: if the step ‘Remote shows other YIO devices’ is also available after setting up the WiFi you can use it to provision newly added YIO devices automatically.

**Comment by carp3-noctem** [comment]
Sharing the Setup via Bluetooth should also be an option. So only one time Setup and then sharing the Information with WiFi or Bluetooth between all remotes.

**Comment by martonborzak** [comment]
I quite like this idea @carp3-noctem

**Comment by martonborzak** [comment]
Access point mode implemented. Bluetooth sharing still needs to be done.

**Comment by martonborzak** [comment]
Implemented
