### ISSUE TITLE
Display won't come out of standby

### ISSUE THREAD

**Issue by martonborzak** [YIO-Remote/remote-software#328]
I couldn't figure out what causes the issue, but my guess is when the proximity sensor and the button or touch wakeup happen at the same time, the standby control gets confused and the remote display stays in standby mode.

Waiting one cycle of dim>standby won't help.

Need to test it further.

**Comment by martonborzak** [comment]
Further testing shows that the remote app crashes. Need to do more testing to hunt down what causes the issue. So far seems pretty random.

**Comment by ChristianRiedl** [comment]
I also had the problem that it did not came out of from standby. The reason was in **Integration::load**, when no dock can be found, loadComplete was not fired because the condition in the onCreateDone slot never matches.

**Comment by martonborzak** [comment]
That is more related to when it starts up for the first time, isn't it @ChristianRiedl ?
Also if you kill the app while in standby and start up again, you need to wait a standby cycle to cycle out of standby mode again.

**Comment by martonborzak** [comment]
Issue is related to mini media player or the media player. When The media player is no longer playing and the array is empty, the app crashes.

**Comment by martonborzak** [comment]
Tested on macos. The issue is not present.

**Comment by martonborzak** [comment]
Seems to be fixed now. Same ownership issue between c++ and javascript, that we had before with entities and integrations.
