### ISSUE TITLE
Media player entity is mixed up with blinds card

### ISSUE THREAD

**Issue by zehnm** [YIO-Remote/remote-software#330]
**Expected behaviour**

Using the entity type _media_player_ shows the media player controls on the remote.

**Current behaviour**

- Integration: HomeAssistant (Hass.io v192)
- Media player: Sonos
- Remote version: DEV 4. Nov 19

The media player shows up on the remote and clicking on the item opens up the blinds card instead of expected media controls.
Top right X doesn't work and there's no way to get out of this screen. I.e. the remote must be killed / rebooted.

**Detailed description**

config.json: 
```
    "media_player": [
      {
        "entity_id": "media_player.esstisch",
        "friendly_name": "Sonos",
        "integration": "homeassistant",
        "supported_features": [
          "SOURCE",
          "APP_NAME",
          "VOLUME",
          "VOLUME_UP",
          "VOLUME_DOWN",
          "VOLUME_SET",
          "MUTE",
          "MUTE_SET",
          "MEDIA_TYPE",
          "MEDIA_TITLE",
          "MEDIA_ARTIST",
          "MEDIA_ALBUM",
          "MEDIA_DURATION",
          "MEDIA_POSITION",
          "MEDIA_IMAGE",
          "PLAY",
          "PAUSE",
          "STOP",
          "PREVIOUS",
          "NEXT",
          "SEEK",
          "SHUFFLE",
          "TURN_ON",
          "TURN_OFF"
        ],
        "type:": "speaker"
      }
    ]
```
I'm not sure if all features are supported, just copied it from an example...

journald log on the RPi:
```
qrc:/components/blind/ui/Card.qml:74: TypeError: Property 'setPosition' of object MediaPlayer(0x1dfb008, "media_player.esstisch") is not a function
qrc:/components/blind/ui/Card.qml:228: ReferenceError: blindButton is not defined
```
![yio-remote_mediaplayer](https://user-images.githubusercontent.com/17356629/68789936-adb4b500-0646-11ea-9004-77275788a824.jpg)

I will try the latest DEV branch and report back.

**Comment by martonborzak** [comment]
This entity is not done yet.

**Comment by zehnm** [comment]
Ok that explains it. The teaser pictures made me believe the media player is working :-)

**Comment by martonborzak** [comment]
There is the mini media player that pops up when you start playing something. That is working. I am currently working on various design elements of the media player and will implement it ASAP.

**Comment by martonborzak** [comment]
This is fixed with latest commit to dev branch.
