### ISSUE TITLE
App doesn't terminate gracefully and crashes

### ISSUE THREAD

**Issue by zehnm** [YIO-Remote/remote-software#337]
**Expected behavior**
When running the app on Linux, macOS or Windows it can be gracefully terminated without throwing errors.

**Current behavior**
On macOs an error dialog is shown when closing the app saying it crashed.
Error messages are shown in the console on every platform.

**Detailed description**
Console messages:
```
FATAL: yio QThread: Destroyed while thread is still running (/0)
19:53:54: The program has unexpectedly finished.
19:53:54: The process was ended forcefully.
```
Crash dialog on macOS:
<img width="430" alt="Screenshot 2019-11-21 at 20 02 32" src="https://user-images.githubusercontent.com/17356629/69368779-0dd8d600-0c9b-11ea-869c-b505eaa7b0bb.png">

**Comment by zehnm** [comment]
One issue is in BluetoothArea:
- BluetoothThread needs to be closed properly in BluetoothArea's deconstructor

**Comment by zehnm** [comment]
Quick fix without checking if the thread has been started or not:
```
BluetoothArea::~BluetoothArea() {
    m_thread.exit();
    m_thread.wait();
}
```
The Bluetooth thread exits and the FATAL QThread error is gone, BUT the app crashes now with a segmentation fault within the Logger because the instance has already been deleted but other parts are still active and continue logging...

@ChristianRiedl could you make the Logger instance a global object, or do you have a better idea?
Right now it's created in main() and is therefore removed too early during application shutdown.

**Comment by zehnm** [comment]
Next issue: DockThread in DockBase (same as BluetoothThread)

**Comment by martonborzak** [comment]
I think that is true for all threaded things

**Comment by zehnm** [comment]
Got everything terminating gracefully without errors. After cleaning up the Wifi rewrite branch I'll add it to the dev branches of remote-software & integration projects.

**Comment by martonborzak** [comment]
Was this fixed already? @zehnm ?

**Comment by zehnm** [comment]
Yes, it was fixed with the WifiControl merge to dev.
