### ISSUE TITLE
Hardware device abstraction

### ISSUE THREAD

**Issue by zehnm** [YIO-Remote/remote-software#346]
## Expected Behavior or Design

As a software architect I expect a hardware abstraction layer for many reasons. To name a few:
- Enables and simplifies testing
- New hardware is easily integrated
- Devices can be mocked
- Enables support for new platforms or allows to adapt the YIO Remote software to easily run on a regular Raspberry Pi.

## Current Behavior or Design

Hardware interaction code is currently implemented in dedicated classes, e.g. one for the proximity sensor, haptic motor, display etc.  
However, the classes are always instantiated and all device interaction code is wrapped in many `#ifdef __arm__  ... #endif` blocks.  

## Possible Solution

1. Create abstract device interfaces.
1. Move existing code to a subclass of the interface
1. Create mock implementations for non-RPi runtime
1. Create a device factory to instantiate and configure the implementations based on runtime and configuration parameters

## Detailed Description and Additional Information

Affected code in remote-software/sources/hardware:
- apds9960.h / .cpp
- bq27441.h / .cpp
- display_control.h / .cpp
- drv2605.h / .cpp
- interrupt_handler.h
- proximity_gesture_control.h

**Comment by ChristianRiedl** [comment]
Good idea ! Optimum would be to have it in a seperate lib. A YIO-Hardware SDK. 
Maybe without Qt, it is not required on this layer.
I think YIO remote could be interesting for PI fans making their own software.

**Comment by zehnm** [comment]
Well there are a few Qt signals which I see required or at least convenient to have. So that would lead to low-level C / C++ device interaction code and probably a higher level Qt integration providing the signals for the other components.
Most important step now is to start refactoring the code. I already started with the design in the wifi rewrite branch and I'm going to start with this task next week.
Once that's done we can discuss further improvements.

**Comment by ChristianRiedl** [comment]
A lot of files, isn't it a bit over engineered ? But maybe I'm a little old fashioned.

**Comment by zehnm** [comment]
The wifi code has been rewritten and merged into the develop branch. It will serve as the foundation for refactoring the hardware specific classes with factories and platform specific includes.

In my opinion this is not over engineered but clearly separated code following well established software design patterns. Probably not yet C/C++ perfect since I'm still having some language issues coming from Java. But I'm confident that it provides us the much needed flexibility and an easy start for new developers or platforms we'd like to support.

I'm starting a feature branch now for refactoring the affected code.
