### ISSUE TITLE
RGB Support for light bulbs

### ISSUE THREAD

**Issue by Tosko4** [YIO-Remote/remote-software#35]
Currently we only have the option to turn the lights on or off, and dim the lights.

**Comment by martonborzak** [comment]
This is not that hard to implement, and right now I am working on finishing up the light component, so I'll move this to implementation.

**Comment by martonborzak** [comment]
Just putting it here for reference:
```
# Bitfield of features supported by the light entity
SUPPORT_BRIGHTNESS = 1
SUPPORT_COLOR_TEMP = 2
SUPPORT_EFFECT = 4
SUPPORT_FLASH = 8
SUPPORT_COLOR = 16
SUPPORT_TRANSITION = 32
SUPPORT_WHITE_VALUE = 128
```
