### ISSUE TITLE
Add guidelines in CONTRIBUTING file

### ISSUE THREAD

**Issue by zehnm** [YIO-Remote/remote-software#350]
## Expected Behavior
As a new contributor I'd like to easily find the contribution guidelines to find out how things are done in a project, what's expected from a contributor and whom to contact for help.

## Current Behavior
No official contribution guidelines available.

## Possible Solution
Write contribution guidelines in CONTRIBUTING.md

## Detailed Description and Additional Information
- [GitHub doc](https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors)
- Example of a good CONTRIBUTING file: [meteor/CONTRIBUTING.md](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md)

**Comment by martonborzak** [comment]
Started creating a draft. Any input? Please contribute :) @zehnm @nklerk @carp3-noctem
https://github.com/YIO-Remote/remote-software/blob/contributing/.github/CONTRIBUTING.md
