### ISSUE TITLE
Light scenes on Yio Remote

### ISSUE THREAD

**Issue by Tosko4** [YIO-Remote/remote-software#36]
Would be wonderful to be able to active a light scene based on what you set it up to do. Like: movie mode. Dim some lights, turn off others. All in one press of a button.

**Comment by gvdhoven** [comment]
I think it should 'extend' light scenes, but be more of a recipe in general; what if you want to close your curtains or blinds as well? Switch inputs to devices (future use case)? I would love to see that 'recipes' can combine multiple devices from multiple categories;

E.g. movie mode recipe 'power on' command:
- Close curtains if during the day
- Turn off all lights except..
- ..

E.g. movie mode recipe 'power off' command:
- Open curtains but only if the movie stopped playing while still light outside
- Turn on all lights

Maybe HA supports something flow-wise like this out of the box?

**Comment by martonborzak** [comment]
HA supports this already. I think this should not be a priority at the moment. But at a later stage could be a nice feature where you can combine multiple hubs and devices into scenes.

**Comment by gvdhoven** [comment]
Yes, exactly what i'm talking about :) Maybe using node-red or something..
