### ISSUE TITLE
Logger: invalid line endings

### ISSUE THREAD

**Issue by zehnm** [YIO-Remote/remote-software#360]
## Description
The logger uses invalid hard coded line endings: `\n\r`.

## How to Reproduce
1. Start app
2. Open logfile
3. See error

## Expected behavior
Line endings must match the platform:
- Windows: `\r\n`
- Unix: `\n`

## Your Environment

* Version used: dev branch
* Running on:
  - [x] YIO Remote
  - [x] Desktop
* Operating System and version: 
macOS, Linux, Windows 10, YIO remote-os

## Additional context
Use Qt platform aware `endl` and don't hard code line endings:
```
    QFile qFile("foobar.txt");
    if (!qFile.open(QIODevice::WriteOnly | QIODevice::Truncate | QIODevice::Text)) {
        return false;
    }
    QTextStream out(&qFile);
    out << "foo" << endl;
    out << "bar" << endl;
    qFile.close();
```

**Comment by ChristianRiedl** [comment]
Fixed, pull logger_integrations

**Comment by zehnm** [comment]
Merged. Please create a dedicated branch & PR for fixes in the future
