### ISSUE TITLE
Kodi support

### ISSUE THREAD

**Issue by miloit** [YIO-Remote/remote-software#366]
Hey guys,
Would be perfect to get a Kodi support.

Regards

**Comment by zehnm** [comment]
Please provide more details on how you envision Kodi support.
If Kodi is integrated as media player into home-assistant or another supported backend then there's already basic support in YIO. But I don't think that's what you are looking for ;-)
Before anyone starts coding we should have a good understanding what users are expecting. Not everyone is using the same features or has the same priorities.

Kodi support should be coordinated with Plex:
https://community.yio-remote.com/t/plex-two-way-ip-support/423

Personally I have Plex as server backend and Kodi (actually LibreELEC) as player with the [PlexKodiConnect](https://github.com/croneter/PlexKodiConnect) plugin for a seamless integration. So I'd like to have Kodi support as well.

**Comment by miloit** [comment]
Hello,
Would be good to have the same features as yatse remote see: https://yatse.tv/
