### ISSUE TITLE
Right to left languages support - Yuvalkob

### ISSUE THREAD

**Issue by Tosko4** [YIO-Remote/remote-software#37]
Submitted by: Yuvalkob - [link](https://community.yio-remote.com/t/right-to-left-languages-support/54)

Hi
I think that Hebrew/Arabic (or any other right to left language) support will be nice. I think that QT can handle it nicely (According to the examples, no other GUI changes needs to be done in order to support this feature)

**Comment by martonborzak** [comment]
I think if we have the translation this will work automatically.
