### ISSUE TITLE
Add generic switch entity

### ISSUE THREAD

**Issue by GileanEU** [YIO-Remote/remote-software#375]
I am using quite a few of different switches (on/off) in Home Assistant, mainly Sonoffs with Tasmota firmware on them, and plan to add Tasmotized Sonoff S20 power plugs as well to replace not-so-reliable Nexas that are RF power plugs. So I would love to ditch my Nexa plugs AND separate Nexa remote and be able to control all those switches with YIO-remote instead!

I think many of us are using some sort of switches in their home automation so this would be a great feature addition to YIO remote as well!

**Comment by martonborzak** [comment]
Proposed properties and attributes:
- States: On, Off
- Supported features: Power meter
- Commands: Toggle, On, Off

**Comment by GileanEU** [comment]
Those should work just fine I think, and although for example Sonoff S20 does not have power meter features, some other wifi/zigbee/z-wave switches might have that so I think it's good to have support for that as well!

**Comment by martonborzak** [comment]
Added a switch entity type.
Todo:
- [x] UI implementation
- [x] Add to integrations
