### ISSUE TITLE
Support for BT beacons - HeinzS

### ISSUE THREAD

**Issue by Tosko4** [YIO-Remote/remote-software#38]
Created by HeinzS - [link](https://community.yio-remote.com/t/support-for-bt-beacons/59)

One possibility for the extra room in the dock is to add a BT beacon such as : https://shop.ruuvi.com/product/ruuvitag-3-pack/ 2

This way, a user could carry their remote from room to room and have it automatically pull up the correct profile for that room.

A software example of using rPi with the above is: https://www.instructables.com/id/RuuviTag-and-PiZero-W-And-Blinkt/

**Comment by martonborzak** [comment]
Implemented
