### ISSUE TITLE
Support Hive Heating

### ISSUE THREAD

**Issue by B-Hartley** [YIO-Remote/remote-software#387]
please support Hive Heating :
https://www.hivehome.com/products/hive-active-heating

API info at:
http://www.smartofthehome.com/2016/05/hive-rest-api-v6/

There is a main thermostat. 
And also they have TRVs (radiator valves)

A direct integration or through an automation hub would be fine.

**Comment by martonborzak** [comment]
@B-Hartley if it's supported by Home Assistant or Homey, then it's already supported :)

**Comment by B-Hartley** [comment]
Ok. Looks like it’s ok on home assistant. 
So I guess I’ll give that a go.

**Comment by martonborzak** [comment]
Cool! Check out the guide on how to run the app on your computer:
https://github.com/YIO-Remote/documentation/wiki/development

Let me know if you need help setting it up! For interactivity, I'd suggest[ our chat](http://chat.yio-remote.com).
