### ISSUE TITLE
Hard buttons on remote - AdrianLiteAutomation

### ISSUE THREAD

**Issue by Tosko4** [YIO-Remote/remote-software#39]
Created by AdrianLiteAutomation - [link](https://community.yio-remote.com/t/hard-buttons-on-remote/55)

Hardware - I would like to see back lit buttons to help with distinguishing buttons in the dark.
Software - I think buttons should have 2 configuration possibilities.
1 a uniform input device that always send the same commands no matter what device you are controlling
2 a default command for most screens, but developers have the option to change what a button does depending on what screen/page or device they are on at that time. Eg, the volume button will control the tv volume majority of the time, but when on a Sonos speaker/group it will control that devices volume instead.

**Comment by martonborzak** [comment]
Backlit buttons unfortunately not going to happen in this first hardware release. The buttons are/will be implemented this way by default. I'm closing this issue due to this.
