### ISSUE TITLE
Improve remote entity

### ISSUE THREAD

**Issue by martonborzak** [YIO-Remote/remote-software#390]
Improve the remote entity type and the UI
## Possible Solution
- [x] Implement executing channel switching based on the sequence defined in `config.json`
- [ ] Make hardware buttons configurable from `config.json`, provide default config
- [x] Add channel numbers to UI on a new page
- [x] Add more buttons to the UI based on features
- [ ] Add opening animation
- [ ] Add rearrange option to channels
- [ ] Add list view to channels
- [ ] Add TV guide page and backend

**Comment by cheesykyle** [comment]
+1 for the configurable hardware buttons. For me personally, this is the most important feature. The ability to assign them to scripts, rest_commands, etc from Home Assistant really makes the remote complete. To be able to assign the buttons for Media Player entities and others would create a lot of flexibility for different use cases.
