### ISSUE TITLE
Improve climate entity

### ISSUE THREAD

**Issue by martonborzak** [YIO-Remote/remote-software#391]
Improve the remote entity type and the UI
## Possible Solution
- [x] Add current temperature to open state UI
- [x] Add opening animation

**Comment by cheesykyle** [comment]
Currently the entity is hard coded for Celsius, including the max and min temperatures. This makes it impossible to set the temperature on imperial entities as the temperature ranges are outside of the acceptable range.

Perhaps an option in settings can allow for toggling between metric and imperial units across the board for all entities that may need it.

**Comment by martonborzak** [comment]
> Currently the entity is hard coded for Celsius, including the max and min temperatures. This makes it impossible to set the temperature on imperial entities as the temperature ranges are outside of the acceptable range.
> 
> Perhaps an option in settings can allow for toggling between metric and imperial units across the board for all entities that may need it.

Good point!

**Comment by martonborzak** [comment]
@cheesykyle this should be fixed in the upcoming update.
