### ISSUE TITLE
Implement Network Scan / direct HW control - Carp3-noctem

### ISSUE THREAD

**Issue by Tosko4** [YIO-Remote/remote-software#40]
Created by Carp3-noctem - [link](https://community.yio-remote.com/t/implement-network-scan-direct-hw-control/45)

Would love to see a Feature like:
1- Scan your local Network during first Setup and Check ability to Control found Devices
2- Control devices (e.g. Sonos) direclty via Remote
3- Backchannel to used Backend (Homey, HA, …) to provide control possibilitys

When this is used, the Remote itself doesn’t need a Backend to be used, but can be implemented.

**Comment by martonborzak** [comment]
Scan has been implemented. Direct HW control is dependent on an integration.
