### ISSUE TITLE
Media Player UI Issues

### ISSUE THREAD

**Issue by carp3-noctem** [YIO-Remote/remote-software#404]
## Description
when opening the search / playlist site, a color bleeding from the artwork page can happen (only observed at remote)

## How to Reproduce
1. Go to a Media Player and open it, when music is playing
2. Open / Slide to Search or Playlist side, there is a color bar / edge visible during transition after landing on page

## Expected behavior
no color bleeding to other cards

## Your Environment

* Version used: 0.2
* Running on:
  - [x] YIO Remote

**Comment by martonborzak** [comment]
Can you take a picture or video @carp3-noctem?
