### ISSUE TITLE
IOBroker Integration

### ISSUE THREAD

**Issue by KarlKiel** [YIO-Remote/remote-software#412]
As I am in the state of trying to bring everything together in IOBroker - I would love to see an integration of YIO remote into IOBroker to enable control of all IObroker available devices (which brings also nice integrations that are currently not available in any of the supported tools like e.g. working digitalstrom support...)

**Comment by zehnm** [comment]
Unfortunately nobody in the core team uses IOBroker. 
Please contact us, if you are interested to take on this task.

**Comment by eviltroooper** [comment]
Maybe someone from the Team can help here?

https://github.com/ioBroker/AdapterRequests/issues/354

**Comment by daes10** [comment]
I backed the V2. And I hope there is full implementation of The YIO Remote in ioBroker when it arrive! ;)

I am very interested about the integration of this remote in ioBroker. But at the moment i don`t have enough skills to programm that. I hope there are some people out there with enough Knowledge.
