### ISSUE TITLE
Prepare application for different screen sizes

### ISSUE THREAD

**Issue by zehnm** [YIO-Remote/remote-software#413]
## Expected Behavior or Design
The screen size should be defined in a single place, accessible to the QML files defining the UI screens.
UI screens must be able to get the actual screen size to be able to adapt to different screen sizes.

## Current Behavior or Design
Screen sizes are hard coded in the QML files. E.g.:
```
Item {
    id: container
    width: 480; height: 800
```

## Possible Solution
The screen size is configurable in `hardware.json` as optional `display/size` object. Example:
```
{
    "display": {
        "control": {
            "enabled": true
        },
        "size": {
            "width": 480,
            "height": 800
        }       
    },
   ...
```
The width and height values are made available to QML either through the HardwareFactory object or setting new properties in the QQmlApplicationEngine. The best way will be evaluated during the implementation and depends on access patterns (performance impacts etc).

## Detailed Description and Additional Information
This change only lays the ground work to support dynamic screen sizes in the future:
- Making the screen size configurable.
- Refactoring the hard coded sizes in the QML files.

It does NOT yet include dynamic screen layouts or a responsive UI design!

**[edit 01.03.20] Further information:**

Qt already provides detailed information about the screen properties. This includes pixel & physical size, scaling factor, logical & physical dpi and others!
See:
- [QDesktopWidget](https://doc.qt.io/qt-5/qdesktopwidget.html)
- [QScreen](https://doc.qt.io/qt-5/qscreen.html)
- [Screen QML Type](https://doc.qt.io/qt-5/qml-qtquick-window-screen.html)

For environments and devices where Qt cannot query the screen information from the device itself, there are environment variables to configure the device properties.  See [Qt for Embedded Linux](https://doc.qt.io/qt-5/embedded-linux.html) for further information. 
On the YIO remote hardware the following eglfs environment variables are set when launching the remote app:

- `QT_QPA_EGLFS_PHYSICAL_WIDTH=46`
- `QT_QPA_EGLFS_PHYSICAL_HEIGHT=76`

With `QT_QPA_EGLFS_WIDTH` and `QT_QPA_EGLFS_HEIGHT` the screen size in pixels could be set as well.

Summary:
- The built-in Qt support provides all required APIs to query screen properties within the app.
- Screen properties are not always available from the environment / driver, but can be set through environment variables.
- Enhancing the app configuration with screen size still makes sense for the following scenario:
  - Running the app as a window on a desktop
  - Testing new screen sizes
  - Fallback configuration if not defined in the environment

**Comment by martonborzak** [comment]
I would suggest to have it in the `Style.qml` singleton as the display resolution is connected to all the other UI related things like colors, typefaces and icons.

**Comment by bobzer** [comment]
Thank you for this enhancement this is great :+1: 
maybe we could take this opportunity to implement dpi ?  (don't know if is needed? maybe interesting because if we start to add different screen size, there is a big difference between a 3.5" and a 7"...)
I understand your point marton but the resolution is more a hardware thing so i think it make more sense to be with other hardware related definition ?

**Comment by martonborzak** [comment]
Yes, defined in the hardware configuration, but then we load it into Style.qml.
Maybe we can add physical size next to the resolution, that would take care of the DPI. Or it’s actually more descriptive when we are talking about UI design. 

But as @zehnm wrote, this is just a hardware/config enhancement. Making the UI responsive is a different story and requires more design work.

**Comment by bobzer** [comment]
yes totally agree, sorry i miss understood when you talk about styles

**Comment by martonborzak** [comment]
Just realised that `Style.qml` won't be a good place to store width/height. Probably needs to live in the `config`.

**Comment by zehnm** [comment]
I have just updated the issue description: Qt already provides extensive information about the screen!
I will still implement the screen configuration as a fallback or override mechanism and the used values will be logged.

**Comment by martonborzak** [comment]
That simplifies a lot @zehnm
