### ISSUE TITLE
Missing keys and features in virtual keyboard

### ISSUE THREAD

**Issue by martonborzak** [YIO-Remote/remote-software#414]
## Description
Missing capital letters and special characters in the virtual keyboard.

**Comment by zehnm** [comment]
I've added `high priority` since I can't connect to WiFi with the new initial setup flow. My WiFi password contains capital letters and special characters...

**Comment by martonborzak** [comment]
@zehnm Could you check these if we need to add more special characters?
![Screenshot 2020-02-29 at 13 52 21](https://user-images.githubusercontent.com/23139408/75607777-d039e380-5afa-11ea-849b-5423b8c0bfa1.png)
![Screenshot 2020-02-29 at 13 52 28](https://user-images.githubusercontent.com/23139408/75607778-d29c3d80-5afa-11ea-9e3b-0127d5a73b52.png)
![Screenshot 2020-02-29 at 13 52 35](https://user-images.githubusercontent.com/23139408/75607781-d3cd6a80-5afa-11ea-8593-97f6c4993b10.png)

**Comment by zehnm** [comment]
@martonborzak We are in a bit of trouble here! There are many many characters missing.
WPA security allows not only all printable ASCII characters, but also Unicode! Technically it's just a 63 byte array.

My suggestion:
- At the very minimum we need all common printable ASCII characters.   
  - E.g.: äöüàáãéèçêñ... + 'all the others & upper case'
  - Comma seems to be missing too
- Unicode is a special case and I don't think we can handle that with a virtual keyboard on the remote.
- For all non-Western regions we fall back to the old access-point configuration, or tell the user to ssh into the remote and configure wpa_supplicant manually.

**Comment by martonborzak** [comment]
@zehnm the alternative characters are there when you press and hold on a button. Same is true for the comma/etc.

https://www.dropbox.com/s/6de6e6w5lqai4vo/Screen%20Recording%202020-02-29%20at%2014.28.08.mov?dl=0

**Comment by martonborzak** [comment]
@zehnm I will add support for multi-language keyboards. So you'll be able to change the keyboard to any locale we support.

**Comment by zehnm** [comment]
Ok, then it's not that bad. The 'press and hold' button for special characters is ok, but the comma should be on the main screen. Otherwise it's not intuitive and I would never find it :-(
In my opinion the following characters should not be on the main screen, because they are barely used: `√½«»®§”™`. Better put `,` and `~` there.

**Comment by martonborzak** [comment]
I've added functionality that the virtual keyboard language now matches the system language. But you can change the keyboard manually if you want. This should cover most of the needs. I am adjusting the special characters as well.
