### ISSUE TITLE
Seg Fault in valijson on certain platforms

### ISSUE THREAD

**Issue by zehnm** [YIO-Remote/remote-software#415]
## Description
The development branch seg faults on certain platforms (e.g. Ubuntu 19.10) with a reference to valijson

## How to Reproduce

1. Create a debug build
1. Run
1. Seg Fault

## Expected behavior
No crash :-)

## Your Environment
* Version used: develop branch
* Running on:
  - Desktop
* Operating System and version: Ubuntu 19.10

## Additional context
- Doesn't crash on macOS or on the remote
- Workaround 1: use release build, no seg fault there
- Workaround 2: remove JSON schema files to the validation is skipped

Solution: downgrade valijson to the last release with only JSON schema v4 support. The used development branch with initial v6/7 support isn't ready yet.

Differences of JSON schema versions: <https://www.codeproject.com/Articles/1233937/Introduction-to-JSON-Schema#spec-v6>

**Can anyone recommend an alternative C++ JSON validation library?**

**Comment by martonborzak** [comment]
This should have been closed because the pull request #417 was merged.

**Comment by zehnm** [comment]
@martonborzak issues are auto-closed once they are merged into the default branch, which is master.
