### ISSUE TITLE
Enhance blinds capabilities for shades

### ISSUE THREAD

**Issue by KarlKiel** [YIO-Remote/remote-software#416]
Besides the pure open/close blinds there are more and more buildings using blinds with shading capabilities (louvre). These additionally offer the possibility to turn the elements to let light go throgh but still give shade of direct sun beam.

Would be great to extend the blinds functionality by adding control for the position of the elements. (so overall UP/Down + Open/Close)

**Comment by martonborzak** [comment]
@KarlKiel would that make sense that press and holding on the `up` and `down` arrows would open/close the shades, but just tapping them would move them up/down?

**Comment by KarlKiel** [comment]
Hi Martin, holding the button makes sense ideally than it would be good to have at least a step based approach - so holding the button will change blinds in several steps, as different angles will fulfill different tasks - e.g. sun shading will be around 100 - 75% openness whereas sight protection will be at 50 or 25% and than off course  completely closed at 0% openness for darkening up. Standard behaviour - e.g. with my digitalstromsystem - is 5 -7 steps with a delay of around 2 seconds between running to the next step which allows to release button to keep current position. - Nevertheless if there is a separate screen it would be great to use two sliders - one for the up/down position, one for the angle of the blinds - attached you will find an example how e.g the digitalstrom app is currently implementing it.
![Screenshot_20200511-204408_dS Smart Home](https://user-images.githubusercontent.com/59452696/81599090-958cdb00-93c8-11ea-8bdc-c6715afed26b.jpg)

**Comment by martonborzak** [comment]
Thanks for the example and explanation @KarlKiel ! Will take a detailed look at it and come up with a way to implement it.
