### ISSUE TITLE
WiFi settings: connected network shows up in other networks

### ISSUE THREAD

**Issue by zehnm** [YIO-Remote/remote-software#420]
## Description
The connected network also shows up in the other networks list.

## How to Reproduce
1. Go to Settings
2. Click on Wifi & bluetooth
3. Make sure you are connected to an AP
4. See the connected network in `other networks`

## Expected behavior
The connected network should not show up in the available network list.

## Your Environment
* Version used: develop / softwareupdate branch
* Running on:
  -  YIO Remote

**Comment by martonborzak** [comment]
I am using `wifi.networkScanResult` to create a list of available networks. A solution could be to create a new array where we filter out the current network (`wifi.wifiStatus.name`). Or we simply hide that item, where the result is the same as the current network.
