### ISSUE TITLE
Wi-Fi Setup Passcode Input Enhancement

### ISSUE THREAD

**Issue by carp3-noctem** [YIO-Remote/remote-software#429]
**Is your feature request related to a problem? Please describe.**
When typing in Wi-Fi Credentials it is hard to know if the pressed Keys are correct. There is no number to * Transition in the Passcode field (as in iOS as example), nor an option to display the Credential in Plain Text.

**Describe the solution you'd like**
Implementation of a visible / unvisible button for the credentials.
Or implement both to directly check the Inout done and make Visible / unvisible.

**Comment by zehnm** [comment]
Furthermore, the password field doesn't have input focus, i.e. one first needs to tap into the field before typing in the password.
Users should be able to directly input the password after the screen changes.
