### ISSUE TITLE
Unable To Update Config

### ISSUE THREAD

**Issue by Shepless** [YIO-Remote/remote-software#434]
## Description
On the latest build of the remote software and also home assistant integration, I cannot update the remotes configuration, it just shows a toast message saying it cannot be updated. After looking at the logs it is valid schema validation:

```
12.05.2020 12:59:15 WARN  json JSON document failed schema validation before writing: "/boot/config.json"
12.05.2020 12:59:15 CRIT  config Write to config file success: false
```
I removed the config-schema.json file to stop any validation at all and it still failed validation.

## How to Reproduce
1. Go to Advanced page in web configurators
2. Don't modify anything
3. Click save and accept the dialog box
4. Observe config is not saved and an error is shown.

## Expected behavior

I should be able update the config, but also the existing config that the remote has loaded (with no modifications) should also save.

## Your Environment

* Version used: 0.3.1
* Running on: YIO Remote

## Additional context
I was trying to add home assistant integration to my remote

**Comment by martonborzak** [comment]
It's probably the schema file. That needs to be revised.

**Comment by martonborzak** [comment]
This was fixed by updating the `config-schema.json`
