### ISSUE TITLE
Please ci Chinese Simplified translation

### ISSUE THREAD

**Issue by sunfang1cn** [YIO-Remote/remote-software#436]
![image](https://user-images.githubusercontent.com/926867/81905683-9fe0ec00-95f7-11ea-8cce-5d86d4701054.png)
I have finished Chinese Simplified translation on crowdin.com , please check in it to new releases

**Comment by martonborzak** [comment]
@sunfang1cn a pre-release is automatically created when a new translation arrives. You can download that and follow the instructions here to manually update the application until we're ready with the software update:
[https://community.yio-remote.com/t/troubleshooting-remote/526](https://community.yio-remote.com/t/troubleshooting-remote/526)
