### ISSUE TITLE
Additional commands added to mediaplayer

### ISSUE THREAD

**Issue by nickprice101** [YIO-Remote/remote-software#449]
Addition of new commands to extend the functionality of the mediaplayer entity.

## Expected Behavior or Design
Add the following context items: SHUFFLE, ADD_TO_QUEUE, CONNECT
Add the following associated commands: SHUFFLE, ADD_TO_QUEUE, GET_SPEAKERS, CHANGE_SPEAKERS
These appear to be pretty generic features that many media players would support. The speakers ones extend the functionality so you change the device you are controlling. For some integrations this is a critical feature as there are many local players.

## Current Behavior or Design
Currently these functions are unavailable.

## Possible Solution
Extend the "arrays" to include these commands. Create QML for displaying the speakers/players and potentially a new SpeakerModel to handle the associated speaker metadata.

## Detailed Description and Additional Information
None.

**Comment by nickprice101** [comment]
ContextMenu QML would also need updating.

**Comment by ChristianRiedl** [comment]
**ContextMenu** QML is inside **basic_ui** so I think it should be completly generic using a list of commands with

- Command text 
- Optional command icon
- Optional formatting and action flags (center, opacity, close)

As the play commands comes from the media player integrations there should be no restriction to  some commands as they are interpreted only by the integrations. Only the used icons require some standardisation, but anyhow this icons are not easy to understand. I don't need them.

And **ContextMenu** should be enhanced to use UP/DOWN buttons and a **selected item** visual presentation. I am not sure if the **ButtonHandler** should be integrated or the client QML sets a **selected item** property. 

The actions should be performed using a callback function **select(index)** which is implemented inside the QML client. This **callback** can be a property of **ContextMenu** (I tested it). A signal **select** is the obvious implementation but harder to use for the dynamically loaded **ContextMenu**.

Than it is justified that **ContexMenu** is part of  **basic_ui** and can be used universally for different purposes.
