### ISSUE TITLE
Add adb support

### ISSUE THREAD

**Issue by nickprice101** [YIO-Remote/remote-software#452]
Add adb to the YIO image so that android devices can be directly controlled.

**Is your feature request related to a problem? Please describe.**
Expands the functionality of the remote so that it can directly interact with common media devices (i.e Fire TV).

**Describe the solution you'd like**
Adb pre-installed on image or via update.

**Describe alternatives you've considered**
Use of proxy such as Home Assistant which does support ADB. Direct control would be better and would allow the development of additional integration options.

**Additional context**
Looking into building a Netflix integration via content API and ADB control.

**Comment by carp3-noctem** [comment]
Peronally i don't like the "speed" of ADB when used to control Devices (e.g. FireTV, SHIELD). So it would be much better, when a Integration provides control of the device itself.

**Comment by nickprice101** [comment]
Totally agree. I'm not aware of any documentation to allow direct control of these devices though? There's obviously a mobile app for control but it's not accessible AFAIK and probably never will be. While it is a a bit slow for navigation it opens up a lot of possibilities for queuing content and producing macro-like functions. I've been running an adb server connection on the remote to trial it  and it works "okay" as in it's usable. I don't know if a direct adb connection would be any faster, but I was hoping it might be? I would say it's comparable if not faster than an external api call. Not a big deal as using an external server works but maybe not practical for some people.

**Comment by bobzer** [comment]
Depending on the need the adb could be great or not. 
If it's just for remote (arrow button, enter, back etc) I think the right way would be to use hid via bluetooth, like that the remote would be paired with the android device and could control it as any other remote and so be really responsive.

**Comment by martonborzak** [comment]
There's bluetooth on the Pi, so it's not that hard to use it. If anyone wants to port this, we would have the basics done and Nvidia Shield support:
https://github.com/Webunity/websocket-to-ble-hid-bridge
https://github.com/Webunity/neeo-driver-nvidia-shield

Obviously we can skip the websocket part :)

**Comment by nickprice101** [comment]
Okay. Challenge accepted (although I’m sure someone else could do it better). Tbh I never thought about Bluetooth. Doh. I guess there is still a place for ADB and intents though as this would just provide HID control I guess rather than being able to launch specific content or query the device?

**Comment by martonborzak** [comment]
I don't know what's possible over Bluetooth, but I assume some commands should be. Qt has a great Bluetooth API, so it shouldn't be too hard. Maybe you can start here, looking at how the dock communication works:
https://github.com/YIO-Remote/remote-software/blob/master/sources/bluetooth.h

**Comment by bobzer** [comment]
i'm not sure adb is doable over bluetooth but beside that, yes adb can be interesting for instance to have a button that open netflix, or you prefered game or apps etc. it offer a lot more control than just hid.

**Comment by Nelus82** [comment]
I don’t have any programming skills, but maybe I could help. I’m a user of the Bluetooth websocket and neeo driver.

In the past i’ve used adb and its to slow.

**Comment by Nelus82** [comment]
Maybe a combination in the future. Adb for the shortcuts and the websocket for the hid navigation.
