### ISSUE TITLE
Update `media_player` entity type

### ISSUE THREAD

**Issue by martonborzak** [YIO-Remote/remote-software#464]
The `media_player` entity type needs to be updated with

- [ ] multiroom support
- [ ] make use of media types

Related issues:
#450 #449 #421 #283

**Comment by martonborzak** [comment]
![Screenshot 2020-06-11 at 12 17 01](https://user-images.githubusercontent.com/23139408/84373883-7d81c480-abdd-11ea-89e9-60289940e902.png)

Design sketches for the multiroom part of the UI.
When you tap on the `speakers` icon, you would see all the groups playing with option to change their volumes.
Tapping on the `down-arrow` will open up the group and you'd see all the speakers that can join that group. Here you can either join a speaker to that group or leave the group.

**Comment by Luckyman7471** [comment]
What requirements do I need in Homeassistant?
I have a mpd player and snapcast clients in homeassistant.

![image](https://user-images.githubusercontent.com/75265948/105629983-7e065d00-5e46-11eb-8af7-3a5f9f865f71.png)
