### ISSUE TITLE
Physical button press and releases are sometimes skipped

### ISSUE THREAD

**Issue by wayfarer003** [YIO-Remote/remote-software#467]
## Description
In working with the remote 0.4.1-4, I find that quite often a press or release of the same physical button often results in a missing state change.  This can be problematic for certain devices suck as a Roku where a long button press can be used to navigate much faster thru the menus....ie press and hold.

I took a look at the code and I noticed the following code segment:
// mcp23017_interrupt.cpp :  line 126
if (gpioVal == 0){
// check the MCP23017 what caused the interrupt
 int e = mcp.readInterrupt();
emit interrupt Event(e);
}
delay(10);

Which was interesting as the mcp23017 should be using interrupts so no need to check the state of the GPIO.

When I removed the check (and the delay) I found that the remote was generating an interrupt storm.  Which is, again, weird because just reading the value from the CLI doesn't show the value changing that often.

My suspicion was that the file watcher was broken and we had a polling loop rather than an actual interrupt.

I changed the notifier from a QSocketNotifier to a QFileSystemWatcher.
After this changed, the behavior now reflects that this is an interrupt as my monitoring only fires (generally) when a button is pressed.

Note....this did not completely eliminate the missing button states...and I also see an occasional interrupt storm which appears to be from the APD9960 sensor.

I don't know QT well enough to know if this method results in more or less CPU usage / batter drain.  
My second issue is that I still see button state being missed and the higher level logic really only toggles between the two states rather than confirming the physical button status.

My changes are in mcp23017_interrupt.cpp: line 102
auto notifier = new QFileSystemWatcher(this);
notifier->addPath(m_gpioValueDevice);

connect(notifier, &QFileSystemWatcher::fileChanged, this, &Mcp23017InterruptHandler::interruptHandler);

## How to Reproduce
This behavior happens without any specific effort.

## Expected behavior
Logical button state should follow the physical button state.

## Your Environment
YIO-Remote

**Comment by martonborzak** [comment]
The MCP23017 is connected to the Pi with one GPIO. So when there's an interrupt on the MCP23017, we don't know what caused that. That's why we need to read the registers after every interrupt to check.

I don't know if QFileSystemWatcher is better or not, but I will test it for a couple of days to see if there's a difference in battery life.

I have to look up the datasheet of the expander IC to see if we can read out the state of the GPIOs. Otherwise we need to keep track of the button states ourselves.

**Comment by martonborzak** [comment]
I've created a feature branch for this: https://github.com/YIO-Remote/remote-software/tree/feature/button-interrupt-fix

**Comment by martonborzak** [comment]
@wayfarer003 I have been testing this for a couple of hours and it seems like it works. I haven't noticed any higher CPU usage. Actually the whole UI seems snappier :) Probably because of the constant trigger before was causing a bit of slowdown :)

**Comment by wayfarer003** [comment]
Ok, nice.  Glad that this is working.
I was thinking about this last night a bit and I see a couple of areas where the routine could be improved.  But, I am not sure about how it would be coded.

First off, I vote that we remote the GPIO is 0 check as I believe this could be a source of missing interrupts.  We don't really know how fast the rPi is in servicing this and if its late we would have missed an event. 

Move the check for the APDS9960 out of the switch statement.  Its an async event and might fire simultaneously as a button.  I would argue that it should just be a IF..Then right before the return -1 as this is the lowest priority device....ie if  you are pressing buttons we shouldn't care about the presence detection.
So, fetch both interrupt results up at the top and then test for them.  This should makes things a little more consistent as there wouldn't be the extra delay on the reads of bank B.
(In my testing, this still doesn't remove the lost button releases)

It should be possible to read the GPIO state by reading from MCP23017_GPIOA & MCP23017_GPIOB.  I don't quite know how to do this but I believe that the interrupt should return both the button and its state.  Maybe by creating a discrete DPAD_UP_PRESS in addition to the DPAD_UP [release].

**Comment by martonborzak** [comment]
Thanks again @wayfarer003! Good points! I've adjusted the code, so now after every interrupt I am reading the GPIO state of the GPIO expander and sending a signal according to that. If you want, you can give it a try in `feature/button-interrupt-fix`

**Comment by wayfarer003** [comment]
Gave it a try.  Seems pretty solid so far.
I don't see any apparent button press skips like I was seeing before.
Hopefully, others will be able to tell....I was previously seeing at times where the remote would advance the setup menu upon button release rather than press...not seeing that anymore.
