### ISSUE TITLE
Button press during "Dim" is ignored / skipped

### ISSUE THREAD

**Issue by wayfarer003** [YIO-Remote/remote-software#470]
## Description
When the remote is in power state "DIM" if physical button is pressed the remote will transition out of this power state to "ON".  But, the button press itself will not take action.
This seems counter intuitive as the remote is still "on" and should be able to respond. 

## How to Reproduce
1.  Allow remote to enter DIM mode.
2.  Press a physical button such as Left / Right.

## Expected behavior
My expectation is that the button effect should be taken and the remote should transition to "ON".

## Your Environment
  - YIO Remote

**Comment by martonborzak** [comment]
This was done like this on purpose. Exception is the volume keys. You might not see the display well and pressing a button would do something unexpected if you think you're in a different part of the app.

**Comment by wayfarer003** [comment]
ok.  What about changing this to be a setup option and switching this to a RFE instead of a bug ?

**Comment by martonborzak** [comment]
Sure. Not sure if it's worth the effort to code this. But let's change it to a feature request and see if  how many would like this as well. It will be low priority at the moment.
