### ISSUE TITLE
Hardware buttons long-press support for remote entity

### ISSUE THREAD

**Issue by pr11me** [YIO-Remote/remote-software#484]
**Is your feature request related to a problem? Please describe.**
The remote entity doesn't support long-press of the hardware buttons. This makes navigation and volume changes very tedious.
\
**Describe the solution you'd like**

Long-pressing volume and navigation buttons would send the command repeatedly. Ideally, this would apply to the OK-button, too, which is useful for e.g. the Nvidia Shield and Kodi. In this case another button/combination needs to be assigned in order to  power off the remote.

**Comment by martonborzak** [comment]
The OK button won't work with long press, as it's hardwired to turn the remote off on a hardware level. This way even if the system becomes unresponsive, you can still turn the remote off.

**Comment by wayfarer003** [comment]
I would also like to add in the touch screen buttons to this ask.
At the moment, they only emit upon an onclick which is effectively a release.
It would be ideal if they would emit a press and release.
This would be useful with Roku and any other device that allows for press and hold operations to speed up navigation.
