### ISSUE TITLE
Use non-privileged port for websocket server

### ISSUE THREAD

**Issue by zehnm** [YIO-Remote/remote-software#489]
## Expected Behavior or Design
The yio-remote app should not only run on the remote, but also on Linux, macOS and Windows desktops.
Currently, the websocket server cannot be started on Unix systems when the app is running with a regular user account.

## Current Behavior or Design
YIO uses port 946 for the websocket server, which is a privileged port that only root is allowed listening on.

## Possible Solution
Use a non-privileged port, e.g. 1946.
Optionally, make it a configuration option.

## Detailed Description and Additional Information
This will also help preparing the remote-os introducing a restricted user account for the remote app instead of using root.

**Comment by martonborzak** [comment]
This also affects the web-configurator and that also needs to be changed.

**Comment by zehnm** [comment]
Yes, this is a breaking change and needs to be coordinated. Probably best to plan it for the next major release.
If we want to make it configurable, then we can already implement it and do the switch when we see fit. That would also have the benefit, that Linux desktop users can already change it on their systems.

**Comment by zehnm** [comment]
Please comment:
- Any suggestions for a better port than 1946?
- Make it configurable?

**Comment by martonborzak** [comment]
Making it configurable could cause more confusion I think. The web configurator also needs to be changed to be configurable then. I would say let's change to 1946 or any other port that works.
