### ISSUE TITLE
Option to set clock/time format to 12 hr

### ISSUE THREAD

**Issue by Diegoale2000** [YIO-Remote/remote-software#493]
so far we are able to change timezone through SSH, but no way to set the clock to 12 hr format.

**Comment by zehnm** [comment]
I suggest to create a new setting for 12 / 24h mode and don't tie it to the existing imperial / metric setting.
As a second step we should add an option to change the timezone from the UI (or web-configurator).

@martonborzak is it ok for you that I'll add a new configuration entry and try to change the display format? I'll leave the settings screen for you :-)

**Comment by martonborzak** [comment]
@zehnm sure it's fine with me :)

**Comment by zehnm** [comment]
Required changes:
- Configuration:
  - Add 24h clock boolean property. Default = true
  - Enhance config json schema
- UI:
  - StatusBar.qml: `timeText.text =  Qt.formatDateTime(new Date(),"hh:mm")`
  - Retrieve 24h clock setting from configuration and set time format accordingly
  - ChargingScreen.qml retrieves value from StatusBar

Nice to have:
- Add 24h clock option in UI settings page
- Enhance web-configurator

**Comment by zehnm** [comment]
Currently testing the implementation, PR follows soon.
| Menubar | Configuration |
|-|-|
| <img width="296" alt="12h-clock-menubar" src="https://user-images.githubusercontent.com/17356629/90331974-26bbb100-dfb9-11ea-9b10-763846076dc8.png"> | <img width="296" alt="12h-clock-settings" src="https://user-images.githubusercontent.com/17356629/90331958-fd028a00-dfb8-11ea-9a3b-aa2bc7ded47b.png"> |

**Comment by zehnm** [comment]
New issue: 12h time format doesn't fit anymore on the charging screen.
Solution: smaller font or display am/pm on new line
