### ISSUE TITLE
Battery Capacity as parameter in the settings

### ISSUE THREAD

**Issue by miloit** [YIO-Remote/remote-software#498]
## Current Behavior or Design
Only 2500mAh Batteries are useable without recompiling the source code. But there are bigger capacity on the market with the same size 

## Possible Solution
Change the variable to a parameter to use also bigger capacity of the batterie
https://github.com/YIO-Remote/remote-software/blob/d67370964b601b4628f9065fa9c1c6c9b55b5b49/sources/hardware/batteryfuelgauge.h#L76

## Detailed Description and Additional Information
Change the variable to a parameter

**Comment by zehnm** [comment]
- The battery capacity can be configured in `hardware.json`: batteryFuelGauge.capacity
- This file is located in `/opt/yio/app/hardware.json`
- Attention: at the moment this file will be overwritten when remote-software is updated!  
  A similar handling as with the main configuration file config.json might be added later.
