### ISSUE TITLE
Factory reset in system menu

### ISSUE THREAD

**Issue by zynexiz** [YIO-Remote/remote-software#505]
Today it's pretty tricky to do a factory reset on the remote, either you need to flash the SD-card with a downloaded image or know what files to more/delete/create to achieve the same. An mentioned [here](https://community.yio-remote.com/t/remaining-yio-kits-are-available/601/61), another way would be to add a button to the system settings that run a script that do this.

In the post, zehnm explained that a reset does the following steps:

- creates a backup of the configuration: /boot/config.json -> /boot/config.json.old
- eplaces /boot/config.json with the empty configuration template /opt/yio/app/config.json.def
- clears the configured wifi networks. This is done programmatically with wpa_supplicant API calls, but it’s basically replacing /etc/wpa_supplicant/wpa_supplicant-wlan0.conf with /etc/wpa_supplicant.conf
-  creates /firstrun marker file to trigger setup wizard at next boot

Creating a script that activates with a "Factory reset" button underneath reboot and shutdown buttons would make it loot easier.

**Comment by zehnm** [comment]
@martonborzak The reset handling is ready for UI integration. I've already added a button the system menu, but it's disabled. What's missing is a user confirmation before doing the reset. Could you add this?
