### ISSUE TITLE
Remote entity UI has blank pages and areas 

### ISSUE THREAD

**Issue by fanderzzon** [YIO-Remote/remote-software#508]
## Description
The UI shows a blank page and some areas when some buttons isn't mapped in the remote entity. 

## How to Reproduce
1. Go to web configurator
2. Click on advanced and scroll down to the remote entity.
3. Map some buttons to YIO Remote but not all.
4. The software will list blank pages and areas if haven't mapped all buttons.

## Expected behavior
The UI should not list pages and areas if the functions isn't mapped in the configuration file (advanced in web configurator).

## Screenshots
![IMG_1663](https://user-images.githubusercontent.com/4114004/93072515-cbe1ac00-f681-11ea-96c5-21b46bf1e2aa.jpeg)
![IMG_1662](https://user-images.githubusercontent.com/4114004/93072518-cd12d900-f681-11ea-88a7-752999e91927.jpeg)

## Your Environment
* Version used: v.6.0

**Comment by nikos1988** [comment]
I also stumbled across this situation. e.g. the channels page. I solved this with a Repeater model

> // channels
>         Repeater {
>             model: (obj.channels.length > 0) ? 1 : 0
>             Loader {
>                 asynchronous: true
>                 sourceComponent: channelView
>             }
>         }

Not sure if this is an elegant solution, but it works
