### ISSUE TITLE
Dedicate Remote to a Room / Multiroom Support

### ISSUE THREAD

**Issue by carp3-noctem** [YIO-Remote/remote-software#51]
A Room support for the Remote would be awesome, so you can select in which room the remote is and then only use the Hardware dedicated to the applicable room.
Also a switcher / select well to adjust the Room for the Remote would be a nice to have option.

**Comment by gvdhoven** [comment]
Related to #38 ?

**Comment by carp3-noctem** [comment]
@webunity
Can be but is not intend to require a beacon

**Comment by gvdhoven** [comment]
yeah so Area support is there, but these have to be provided by the integrations; e.g. Home assistant has areas for this; is that what you mean?

**Comment by martonborzak** [comment]
If there's no support for that, you'll still be able to assign a room to any entity. So it's not dependent on the integration.
If the integration supports rooms, that is helpful at the setup process, to automatically sort it out. Otherwise it's manual entry.

An entity config entry looks like this:
```
{
    "brightness": "0",
    "entity_id": "light.backdoor_lamp",
    "favorite": false,
    "friendly_name": "Backdoor lamp",
    "integration": "homeassistant",
    "room": "Entrance",
    "state": "off",
    "type": "light"
}
```

Of course we need to change room to area.

**Comment by martonborzak** [comment]
@carp3-noctem You're thinking that the remote would only show one specific room's entities? So won't be able to navigate to another room? Or just set the "start page" to that room?

**Comment by carp3-noctem** [comment]
As initial yes, and then the user can enable or disable other rooms per remote used.

Meaning: when remote is set to living room, this is the only room available on the remote by default.
It makes less sense to switch on / off the light in the basement.
But if a user would like to have control over them, he can enable it.

**Comment by martonborzak** [comment]
> As initial yes, and then the user can enable or disable other rooms per remote used.
> 
> Meaning: when remote is set to living room, this is the only room available on the remote by default.
> It makes less sense to switch on / off the light in the basement.
> But if a user would like to have control over them, he can enable it.

Got it! Thanks!

**Comment by martonborzak** [comment]
I think this can be done with the new improved way we handle the UI. Closing the issue. If not, please reopen it.
