### ISSUE TITLE
Reboot in Dock leads to unreachable remote via ssh after a while

### ISSUE THREAD

**Issue by nikos1988** [YIO-Remote/remote-software#510]
## Description
Rebooting the remote while it is docked leads to unreachability after a while. WiFi is probably shut down.

## How to Reproduce
reboot via ssh while remote is docked
wait x mins until WiFi off timeout is reached

## Expected behavior
while the remote is docked it should be reachable via WiFi all of the time

## Your Environment

* Version used: remote-software v0.6.0
* Running on: 
  - YIO Remote

**Comment by martonborzak** [comment]
Hi,

it's programmed the way you describe as expected behavior. Wifi is always on if it is in the dock and the dock is plugged in.
I tried to reproduce the issue, but all 5 times it was on the network.

Could you try to look into the logs for that specific timeframe where this issue happens?

**Comment by nikos1988** [comment]
[remote_log.txt](https://github.com/YIO-Remote/remote-software/files/5231624/remote_log.txt)

I removed some log entries that belong to my own intergration.

**Comment by nikos1988** [comment]
I added the log. I forgot to mention that I stopped the app via "systemctl stop app" before rebooting.

The remote was at all times in the dock and I did not touch it. 
At "Sep 16 12:16:59" the wifi is stopped. Pretty much 30mins after the reboot. My wifi off timer ist set to 30mins also.
