### ISSUE TITLE
Removing entity in web configurator crashes remote

### ISSUE THREAD

**Issue by jadlers** [YIO-Remote/remote-software#525]
## Description

When I try to remove an entity in the we configurator the remote crashes with a segmentation fault. It's the same both for entities from the `homeassistant` integration and the YIO dock integration. The output on the remote points to [this line](https://github.com/YIO-Remote/remote-software/blob/master/sources/yioapi.cpp#L200) in `yioapi.cpp`.

## How to Reproduce
1. Open the web configurator
2. Go to the page for entities
3. Click the `x` to remove an entity from the `homeassistant` integration
4. It crashes

## Expected behavior

I expect the entity to be removed or an error that the entity could not be removed without the remote crashing.

## Screenshots

![2021-01-18_18-05-36](https://user-images.githubusercontent.com/16165462/104944721-e91fe180-59b7-11eb-8ff1-2165220c3efe.png)

Here's the logs from the remote:
```txt
2021-01-18 17:52:05:891 CET DEBUG [yio.api]:	Request for remove entity "media_player.spotify_j_a_c_o_b" "::ffff:192.168.1.30"	[../sources/yioapi.cpp:1150]
2021-01-18 17:52:05:909 CET DEBUG [yio.api]:	Removing entity: "media_player.spotify_j_a_c_o_b"	[../sources/yioapi.cpp:200]
Segmentation fault
```

## Your Environment

* Version used:  Ran `update.sh -r` on the remote:

   ```txt
  +                              +          +             +
  |  Component                   |  GitHub  |  Installed  |
  +                              +          +             +
  |  remote-software             |  v0.7.0  |  0.7.0      |
  |  web-configurator            |  v0.2.1  |  v0.2.1     |
  |  remote-os                   |  v1.1.0  |  1.1.0      |
  |  integration.dock            |  v0.6.4  |  0.6.4      |
  |  integration.homey           |  v0.5.4  |  0.5.4      |
  |  integration.home-assistant  |  v0.5.7  |  0.5.7      |
  |  integration.openhab         |  v0.5.6  |  0.5.4      |
  |  integration.spotify         |  v0.5.4  |  0.5.4      |
  |  integration.bangolufsen     |  v0.2.5  |  0.2.5      |
  |  integration.roon            |  v0.4.4  |  -          |
  |  integration.openweather     |  v0.5.4  |  -          |
  +                              +          +             +

   ```
* Running on: 
  - YIO Remote

**Comment by zehnm** [comment]
That's a pretty bad one.
Fun fact: when the integration removal is working, then it reboots your Linux development machine! I'll suppress that, so it only reboots the remote.

**Comment by jadlers** [comment]
Thanks for fixing it @zehnm !
Oof, I can understand you were confused when it happened!
