### ISSUE TITLE
Room enumeration in bottom tray of main screen

### ISSUE THREAD

**Issue by owarek** [YIO-Remote/remote-software#83]
Is there an option to change the bottom tray (rooms, lights, blinds, etc.)  to enumeration of rooms? It would be quite "messy" to search for the correct room in lights tab when you have a lot of them. It would be much faster to find correct room in the bottom tray and then the correct device. This would be totaly awesome. Thank you for your work.

**Comment by liteautomation1** [comment]
Great idea. Or even just add a rooms menu option that then displays all room within a system.

**Comment by gvdhoven** [comment]
@liteautomation1 that is the idea; see #88 for current ideas
