### ISSUE TITLE
Change bottom menu to layered layout

### ISSUE THREAD

**Issue by gvdhoven** [YIO-Remote/remote-software#88]
Now we have 'rooms' and the rest; how about we change that to a layered approach?
Areas | Favorites | Recipes | Devices | Integrations
1) Areas instead of rooms; why? because what if i want to add e.g. my irrigation system or Hue lights in the garden?
2) Favorites; self explanatory
3) Recipes; to mimic the Neeo remote behavior or "Scenes" behavior that Hass.io has; e.g. "Movie mode" which can interact with different devices; since recipes CAN overarch areas i would give them a seperate menu item
4) Devices; which contain the "device types" supported which are now next to the rooms
5) Integrations; which allows you to directly interact with an integration e.g. home assistant / domoticz / homey / gardena etc.

Would be great if we can also have this list 'sortable' by end users.
Can be used to enhance #38 and #51 (e.g. preselect room you are in)

**Comment by martonborzak** [comment]
@Webunity I can imagine it in a way that it slides to that area (room) page when it detects the beacon. Could be a nice solution.

**Comment by gvdhoven** [comment]
1) Fixed with https://github.com/martonborzak/yio-remote/commit/2c13cf46e329d31050fd5eedbbe9a115a8464293

**Comment by martonborzak** [comment]
2. Also done.
