### ISSUE TITLE
Notification when sensor value change

### ISSUE THREAD

**Issue by martonborzak** [YIO-Remote/remote-software#94]
Support for sensors that can trigger notifications. For example: a doorbell sensor is on, a notification pops up on the remote

**Comment by Tosko4** [comment]
Or a locked area (garage doors), when the sensor changes state to notify too as an alert

**Comment by gvdhoven** [comment]
I think this one needs some discussion before we start implementing it. because if we do something like a websocket server-ish thingy, and we switch off wifi, we might miss sending out notifications, or be too late.

**Comment by martonborzak** [comment]
Yes. The details need more thoughts but in general as a feature would be nice. 
If we have an esp in the dock and a Bluetooth connection to the remote that could be a solution.

**Comment by gvdhoven** [comment]
What if you have multiple remotes and 1 is for example in the range of the dock and the other one is not (which happens to be the one laying next to you in the kitchen) then you might miss a notification.

**Comment by martonborzak** [comment]
True. But I guess there’s no solution that could make up for range issues.
