### ISSUE TITLE
http server (download, upload backup, restore Files, manage remote)

### ISSUE THREAD

**Issue by carp3-noctem** [YIO-Remote/remote-software#97]
Integration of a lean http server with possibility to get direct access to the remote for e.g.
- download / upload files (e.g. config, pictures, buttons, styles)
- backup & restore config / remote
enhanced feature
- cofigure the remote from website hosted on it

this should be accessible, when remote is on and maybe all the time, when on charger (both Qi & Dock)

**Comment by wayfarer003** [comment]
Suggest adding an auto local backup feature that cycles around some fixed number of copies over some time frame (days/weeks, etc).  This would be to help avoiding the automatic config changes from wiping out your local config file completely.

**Comment by martonborzak** [comment]
Lighttpd is now working on the remote. Can be turned on and off from settings. Just need a frontend to do all the stuff

**Comment by mcarter00** [comment]
What functions do you envision on the frontend?

**Comment by martonborzak** [comment]
> What functions do you envision on the frontend?

Ultimate goal is to have a web based configuration interface. So you don't have to do everything on the remote. Including backup/restore, etc.

**Comment by carp3-noctem** [comment]
Closed, As Webconfig is now available from here: https://github.com/YIO-Remote/web-configurator
