### ISSUE TITLE
Improve the connecting screen

### ISSUE THREAD

**Issue by martonborzak** [YIO-Remote/remote-software#99]
Do not show the connecting screen when no integration is configured.
If more integrations are configured, show them on the connection screen:
Connecting 1/2 Home Assistant
Connecting 2/2 Homey

**Comment by martonborzak** [comment]
![Screenshot 2019-04-29 at 20 54 54](https://user-images.githubusercontent.com/23139408/56919535-1d0af300-6ac1-11e9-876f-0dced0a43527.png)

Design is done for the new notification bar.

**Comment by gvdhoven** [comment]
Few ideas on the left design:
- Maybe have the "1/2" inside the animated circle?
- Why rounded and not square and full width of the remote (just like the "teardrop" info box at the bottom?
- Have that square slide in down behind the time and battery level (and slide up when done)
- Maybe no box but just a string dead center inside that small bar between the time and battery level?

Regarding right design:
- Jikes! that is red!
- Error screen can maybe be centered?
- Which connection failed? What if one succeeds and one fails? Maybe change that to "The connection to [integration name] failed. Click here to update settings and try again" or, in case of of 'x' failed; "The connection to one or more integrations failed. Click here to update settings and try again"
- maybe "try again" + "verify settings" buttons
- red text on black/gray box would also suffice i think :smiley:
- error could maybe be a darkened background (overlay) to indicate user attention is needed?
- "X" suggest you can close the box there? is it?

Just shooting :)

**Comment by martonborzak** [comment]
I'd like to keep all the popups and notifications "over" the UI. These things are not permanent.

Red, because it's error. I'll make a revision that makes it more clean what integration failed.

**Comment by gvdhoven** [comment]
Re-looking at the screens today; what if you move the spinner to the right, so that the text aligns on the left saying "Connecting (1 of 2)" with on the new line "Home Assistant" (because it can also read "Domoticz" / "Homey" or even "SomeFancyLanDevice" (e.g. non-integrations) and then in the error scenario you can switch "Connecting (1 of 2)" to "Connection failed" -> e.g. remove the cross altoghether, it is already an error screen due to the red color

**Comment by martonborzak** [comment]
![Screenshot 2019-05-13 at 22 45 19](https://user-images.githubusercontent.com/23139408/57653354-e3aea900-75d1-11e9-94ea-44f4fc2df670.png)
![Screenshot 2019-05-13 at 22 53 22](https://user-images.githubusercontent.com/23139408/57653363-eb6e4d80-75d1-11e9-8ab6-3aa660456e08.png)

I'll just post here as well for reference.

**Comment by gvdhoven** [comment]
i would remove the "Notifications" label inside the drawer, since it can also be errors and make the rounded corners of the notifications thesame as e.g. Apple TV (same box layout)
